import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../main.dart';

Lang strings = Lang();

class Lang {

  var direction = TextDirection.ltr;
  String locale = "en"; // ISO 639-1

  Map<int, String> langEng = {
    0 : "ModjiDep Provider",
    1 : "PROVIDER",
    2 : "SUBMIT",
    3 : "Language",
    4 : "Preferred Language",
    5 : "Select Preferred Language",
    6 : "Sign in now",
    7 : "Email",
    8 : "Enter your Email",
    9 : "Password",
    10 : "Enter your Password",
    11 : "CONTINUE",
    12 : "REGISTER",
    13 : "or continue with",
    14 : "Register",
    15 : "in less than a minute",
    16 : "Name",
    17 : "Enter Name",
    18 : "Confirm Password",
    19 : "Verification",
    20 : "Phone number",
    21 : "Enter your Phone number",
    22 : "We'll sent verification code.",
    23 : "We've sent 6 digit verification code.",
    24 : "Enter code",
    25 : "Enter 6 digits code",
    26 : "Chat",
    27 : "History",
    28 : "Account",
    29 : "Write your message ...",
    30 : "Any Time",
    31 : "Upcoming",
    32 : "Completed",
    33 : "Canceled",
    34 : "New",
    35 : "Canceled",
    36 : "Completed",
    37 : "Accepted",
    38 : "Call now",
    39 : "Message",
    40 : "Accept",
    41 : "Start a job",
    42 : "Job complete",
    43 : "Waiting for Confirmation from Customer",
    44 : "Booking ID",
    45 : "Request Received",
    46 : "Time",
    47 : "Booking Confirmed",
    48 : "Confirmed on",
    49 : "Start a job",
    50 : "Scheduled on",
    51 : "Job Completed",
    52 : "Payment will appear here",
    53 : "Pricing",
    54 : "Quantity",
    55 : "Tax amount",
    56 : "Total",
    57 : "Press for view profile",
    58 : "reviews",
    59 : "Read all",
    60 : "Change Language",
    61 : "Set your Preferred language",
    62 : "Enter your Email",
    63 : "Address",
    64 : "Enter address for customers",
    65 : "Description",
    66 : "Enter Short description about you",
    67 : "SAVE",
    68 : "Change password",
    69 : "New password",
    70 : "Enter Password",
    71 : "Confirm New password",
    72 : "CHANGE PASSWORD",
    73 : "My Profile",
    74 : "Everything about you",
    75 : "Average Ratings",
    76 : "Enable Dark Mode",
    77 : "Set you favorite mode",
    78 : "Wallet",
    79 : "Know your earnings",
    80 : "My Portfolio",
    81 : "Upload your best works",
    82 : "Privacy Policy",
    83 : "Known our Privacy Policy",
    84 : "From Gallery",
    85 : "From Camera",
    86 : "Delete",
    87 : "Set invisible",
    88 : "Available Balance",
    89 : "Notifications",
    90 : "Lots of important information",
    91 : "Log Out",
    92 : "End the session",
    93 : "Please Enter Email",
    94 : "Please Enter Password",
    95 : "User not found",
    96 : "User is disabled. Connect to Administrator for more information.",
    97 : "Passwords are not equal",
    98 : "Email are wrong",
    99 : "User don't create",
    100 : "You account created. After moderation your account will be activated. We will inform you.",
    101 : "Chatting online",
    102 : "Search",
    103 : "Chat message",
    104 : "Notifications",
    105 : "Lots of important information",
    106 : "Today",
    107 : "Not found ...",
    108 : "About Us",
    109 : "Known About Us",
    110 : "Terms & Conditions",
    111 : "Known Terms & Conditions",
    112 : "Enter your name",
    113 : "Enter Confirm Password",
    114 : "Password changed",
    115 : "Please Enter name",
    116 : "Data saved",
    117 : "Booking status was changed",
    118 : "Now status:",
    119 : "by customer",
    120 : "by provider",
    121 : "by administrator",
    122 : "Money transfer",
    //123 : "My page",
    123 : "Image and Name of my service offers",
    124 : "Edit Provider information",
    125 : "Monday",
    126 : "Tuesday",
    127 : "Wednesday",
    128 : "Thursday",
    129 : "Friday",
    130 : "Saturday",
    131 : "Sunday",
    132 : "Galleries",
    133 : "Edit",
    134 : "Save",
    135 : "Enter your Phone",
    136 : "Enter your Web Page address",
    137 : "Enter your Instagram address",
    138 : "Enter your Telegram address",
    139 : "Change",
    140 : "Add from galley",
    141 : "Add from camera",
    142 : "My published services",
    143 : "Edit Service information",
    144 : "Search service",
    145 : "Do you want to delete this item? You will can't recover this item.",
    146 : "No",
    147 : "This is Demo Mode. You can't modify this section",
    148 : "Edit Service",
    149 : "Visible",
    150 : "Select Language",
    151 : "Tax",
    152 : "Description Title",
    153 : "Price",
    154 : "Discount price",
    155 : "Price Unit",
    156 : "Hourly",
    157 : "Fixed",
    158 : "Select image",
    159 : "Addons",
    160 : "Add addon",
    161 : "Gallery",
    162 : "Image deleted",
    163 : "Add image from gallery",
    164 : "Service duration",
    165 : "min",
    166 : "Only selected",
    167 : "Categories",
    168 : "Providers",
    169 : "Save current service",
    170 : "Please enter price",
    171 : "Please select provider",
    172 : "Please enter category",
    173 : "Save addon",
    174 : "Close",
    175 : "Select",
    176 : "Addon will be deleted from all services in current Provider. Do you want to delete this item? You will can't recover this item. ",
    177 : "Data deleted",
    178 : "Publish a new service",
    179 : "My Work Area",
    180 : "Edit your work area",
    181 : "Delete current",
    182 : "Forgot password?",
    183 : "Reset password",
    184 : "Send new password",
    185 : "Reset password email sent. Please check your mail.",
    186 : "Date",
    187 : "Please Enter phone",
    188 : "Please leave information for us to make it easier for us to work with you.",
    189 : "Provider Name",
    190 : "Home service",
    191 : "Login",
    192 : "Phone",
    193 : "Set my Work Area",
    194 : "Set Provider Logo",
    195 : "Please Enter Provider Name",
    196 : "Please Enter description",
    197 : "Please Enter address",
    198 : "Please upload Provider Logo",
    199 : "Please select work area",
    200 : "Please select Category where you will work",
    201 : "Please Enter Login",
    202 : "Payment method",
    203 : "Subtotal",
    204 : "Discount",
    205 : "User must be Provider",
    206 : "Provider Information not found",
    207 : "Are you sure you want to exit?",
    208 : "Exit",
    209 : "On map",
    210 : "Customer location",
    211 : "Customer address",
    212 : "Enable Notify",
    213 : "Provider Available/Unavailable",
    214 : "Temporary disable your account",
    215 : "VAT/TAX",
    216 : "Total amount",
    217 : "Booking At",
    218 : "Customer name",
    219 : "To Admin",
    220 : "To Provider",
    221 : "TAX/VAT",
    222 : "Payouts",
    223 : "Balance",
    224 : "Orders",
    225 : "My Products",
    226 : "Edit Products information",
    227 : "Search in this list",
    228 : "Create new product",
    229 : "Not available Now",
    230 : "Add image URL",
    231 : "Description:",
    232 : "You can use HTML tags (<p>, <br>, <h1> and other)",
    233 : "Variants",
    234 : "Add new group",
    235 : "Add new variant",
    236 : "Save current product",
    237 : "Add New Product",
    238 : "Unit",
    239 : "In Stock",
    240 : "pcs",
    241 : "Please select variant",
    242 : "Save group",
    243 : "Add group",
    244 : "Group name",
    245 : "Preview",
    246 : "URL",
    247 : "Add image",
    248 : "Variant name",
    249 : "Add image from gallery (optional)",
    250 : "or",
    251 : "Add image URL (optional)",
    252 : "influence on price +/-",
    253 : "Save variant",
    254 : "Add variant",
    255 : "Please select stock",
    256 : "influence must start with + or -",
    257 : "Close",
    258 : "Add image from camera",
    259 : "Add image from camera (optional)",
    260 : "Please upload image",
    261 : "Cancel",
    262 : "You have exceeded the limit on the number of services. Contact support for more information.",
    263 : "Category tree",
    264 : "Price can't be 0",
    265 : "You have exceeded the limit on the number of addons on one service. Contact support for more information.",
    266 : "You have exceeded the limit on the number of products. Contact support for more information.",
    267 : "Minimum order amount",
    268 : "Maximum order amount",
    269 : "Settings",
    270 : "Set minimum amd maximum order amounts",
    271 : "Please enter minimum order amount",
    272 : "Please enter maximum order amount",
    273 : "Allow booking only if customer located in provider work area",
    274 : "@ ModjiDep Fournisseur 2022",
    275 : "By TigerSoft",
    276: "Loading messages...",
    277 : "OK",
    278: "Check your internet connection!",
    279 : "From user :",
    280 : "New request",
    281 : "The status of the request has been changed",
    282 : "Status now: Cancel",
    283 : "Status now: Finish",
    284:"Ready",
    285:"Finish",
    286: "Waiting",
    287 : "No notification",
    288 : "Your profile picture and name",
    289 : "This image and this name of your profile will appear on all your offers of services published in the different categories of your choice. So choose a photo and name that is decent and appropriate enough to entice customers who see your offers to choose you.",
    290: "Invisible",
    291: "Publish",
    292: "Unavailable",
    293: "Delete",
    294 : "Publish",
    295 : "Home",
    296 : "Available",
    297: "Make Available",
    298: "Make Unavailable",
    299 : "Service",
    230 : "Delete your account",
    231 : "Be careful if you confirm, your data will be deleted and you can no longer restore them. this action is irreversible.",
  };



  Map<int, String> langFra = {
    0 : "ModjiDep Fournisseur",
    1 : "FOURNISSEUR",
    2 : "SOUMETTRE",
    3 : "Langue",
    4 : "Langue préférée",
    5 : "Sélectionner la langue préférée",
    6 : "Connectez-vous maintenant",
    7 : "Courriel",
    8 : "Entrez votre Email",
    9 : "Mot de passe",
    10 : "Entrez votre mot de passe",
    11 : "CONTINUER",
    12 : "Inscription",
    13 : "ou continuer avec",
    14 : "S'inscrire",
    15 : "en moins d'une minute",
    16 : "Nom",
    17 : "Entrez le nom",
    18 : "Confirmer le mot de passe",
    19 : "Vérification",
    20 : "Numéro de téléphone",
    21 : "Entrez votre numéro de téléphone",
    22 : "Nous vous enverrons le code de vérification.",
    23 : "Nous avons envoyé un code de vérification à 6 chiffres.",
    24 : "Saisir le code",
    25 : "Entrez le code à 6 chiffres",
    26 : "Discuter",
    27 : "Historique",
    28 : "Compte",
    29 : "Ecrivez votre message...",
    30 : "N'importe quand",
    31 : "À venir",
    32 : "Terminé",
    33 : "Annulé",
    34 : "Nouveau",
    35 : "Annulé",
    36 : "Terminé",
    37 : "Accepté",
    38 : "Appeler",
    39 : "Message",
    40 : "Accepter",
    41 : "Démarrer une tâche",
    42 : "Tâche terminée",
    43 : "En attente de confirmation du client",
    44 : "Identifiant",
    45 : "Demande reçue",
    46 : "Le temps",
    47 : "Réservation confirmée",
    48 : "Confirmé le",
    49 : "Démarrer une tâche",
    50 : "Prévu",
    51 : "Tâche terminée",
    52 : "Le paiement apparaîtra ici",
    53 : "Tarification",
    54 : "Quantité",
    55 : "Montant de la taxe",
    56 : "Totale",
    57 : "Appuyez pour afficher le profil",
    58 : "critiques",
    59 : "Lire tout",
    60 : "Changer de langue",
    61 : "Définissez votre langue préférée",
    62 : "Entrez votre Email",
    63 : "Adresse",
    64 : "Saisir l'adresse des clients",
    65 : "Description",
    66 : "Entrez une brève description de vous",
    67 : "SAUVEGARDER",
    68 : "Modifier le mot de passe",
    69 : "Nouveau mot de passe",
    70 : "Entrez le mot de passe",
    71 : "Confirmer le nouveau mot de passe",
    72 : "CHANGER MOT DE PASSE",
    73 : "Mon Profil",
    74 : "Tout sur toi",
    75 : "Notes moyennes",
    76 : "Activer le mode sombre",
    77 : "Définissez votre mode préféré",
    78 : "Portefeuille",
    79 : "Connaissez vos gains",
    80 : "Mon portefeuille",
    81 : "Téléchargez vos meilleures œuvres",
    82 : "Politique de confidentialité",
    83 : "Connaître notre politique de confidentialité",
    84 : "De la Galerie",
    85 : "Depuis la caméra",
    86 : "Effacer",
    87 : "Définir invisible",
    88 : "Solde disponible",
    89 : "Notifications",
    90 : "Beaucoup d'informations importantes",
    91 : "Déconnexion",
    92 : "Fermer la session",
    93 : "Veuillez saisir un e-mail",
    94 : "Veuillez entrer le mot de passe",
    95 : "Utilisateur introuvable",
    96 : "L'utilisateur est désactivé. Connectez-vous à l'administrateur pour plus d'informations.",
    97 : "Les mots de passe ne sont pas égaux",
    98 : "Email erroné",
    99 : "L'utilisateur ne crée pas",
    100 : "Votre compte a été créé. Après modération, votre compte sera activé. Nous vous informerons.",
    101 : "Discuter en ligne",
    102 : "Rechercher",
    103 : "Message de discussion",
    104 : "Notifications",
    105 : "Beaucoup d'informations importantes",
    106 : "Aujourd'hui",
    107 : "Non trouvée...",
    108 : "À propos de nous",
    109 : "Nous sommes connus",
    110 : "Conditions générales",
    111 : "Conditions générales connues",
    112 : "Entrez votre nom",
    113 : "Entrez la confirmation du mot de passe",
    114 : "Mot de passe modifié",
    115 : "Veuillez entrer le nom",
    116 : "Données sauvegardées",
    117 : "Le statut de la réservation a été modifié",
    118 : "État actuel :",
    119 : "par client",
    120 : "par prestataire",
    121 : "par l'administrateur",
    122 : "Transfert d'argent",
    //123 : "Ma page",
    123 : "Image et Nom de mes offres de services",
    124 : "Modifier les informations du fournisseur",
    125 : "Lundi",
    126 : "mardi",
    127 : "Mercredi",
    128 : "Jeudi",
    129 : "Vendredi",
    130 : "Samedi",
    131 : "Dimanche",
    132 : "Galeries",
    133 : "Modifier",
    134 : "Enregistrer",
    135 : "Entrez votre téléphone",
    136 : "Entrez l'adresse de votre page Web",
    137 : "Entrez votre adresse Instagram",
    138 : "Entrez votre adresse Telegram",
    139 : "Modifier",
    140 : "Ajouter depuis la galère",
    141 : "Ajouter depuis la caméra",
    142 : "Mes services publiés",
    143 : "Modifier les informations de service",
    144 : "Service de recherche",
    145 : "Voulez-vous supprimer cet élément ? Vous ne pourrez pas récupérer cet élément.",
    146 : "Non",
    147 : "C'est le mode démo. Vous ne pouvez pas modifier cette section",
    148 : "Modifier le service",
    149 : "Visible",
    150 : "Sélectionner la langue",
    151 : "Impôt",
    152 : "Titre descriptif",
    153 : "Prix",
    154 : "Prix réduit",
    155 : "Unité de prix",
    156 : "Horaire",
    157 : "Fixé",
    158 : "Sélectionner une image",
    159 : "Modules complémentaires",
    160 : "Ajouter un complément",
    161 : "Galerie",
    162 : "Image supprimée",
    163 : "Ajouter une image de la galerie",
    164 : "Durée de service",
    165 : "min",
    166 : "Seulement sélectionné",
    167 : "Catégories",
    168 : "Prestataires",
    169 : "Enregistrer le service en cours",
    170 : "Veuillez saisir le prix",
    171 : "Veuillez sélectionner un fournisseur",
    172 : "Veuillez saisir une catégorie",
    173 : "Enregistrer l'extension",
    174 : "Fermer",
    175 : "Sélectionner",
    176 : "L'addon sera supprimé de tous les services du fournisseur actuel. Voulez-vous supprimer cet élément ? Vous ne pourrez pas récupérer cet élément. ",
    177 : "Données supprimées",
    178 : "Publier un nouveau service",
    179 : "Mon espace de travail",
    180 : "Modifier votre espace de travail",
    181 : "Effacer courant",
    182 : "Mot de passe oublié ?",
    183 : "Réinitialiser le mot de passe",
    184 : "Envoyer un nouveau mot de passe",
    185 : "E-mail de réinitialisation du mot de passe envoyé. Veuillez vérifier votre messagerie.",
    186 : "Le",
    187 : "Veuillez entrer le téléphone",
    188 : "Veuillez nous laisser des informations pour nous permettre de travailler plus facilement avec vous.",
    189 : "Nom du fournisseur",
    190 : "Service à domicile",
    191 : "Connexion",
    192 : "Téléphone",
    193 : "Définir ma zone de travail",
    194 : "Définir le logo du fournisseur",
    195 : "Veuillez entrer le nom du fournisseur",
    196 : "Veuillez saisir une description",
    197 : "Veuillez saisir l'adresse",
    198 : "Veuillez télécharger le logo du fournisseur",
    199 : "Veuillez sélectionner la zone de travail",
    200 : "Veuillez sélectionner la catégorie dans laquelle vous travaillerez",
    201 : "Veuillez entrer le nom d'utilisateur",
    202 : "Mode de paiement",
    203 : "Sous-total",
    204 : "Remise",
    205 : "L'utilisateur doit être fournisseur",
    206 : "Information fournisseur introuvable",
    207 : "Êtes-vous sûr de vouloir quitter ?",
    208 : "Sortie",
    209 : "Sur la carte",
    210 : "Localisation du client",
    211 : "Adresse client",
    212 : "Activer la notification",
    213 : "Fournisseur disponible/indisponible",
    214 : "Désactiver temporairement votre compte",
    215 : "TVA/IMPÔT",
    216 : "Montant total",
    217 : "Réservation à",
    218 : "Nom du client",
    219 : "À l'administrateur",
    220 : "Au fournisseur",
    221 : "IMPÔT/TVA",
    222 : "Paiements",
    223 : "Équilibre",
    224 : "Ordonnances",
    225 : "Mes produits",
    226 : "Modifier les informations sur les produits",
    227 : "Rechercher dans cette liste",
    228 : "Créer un nouveau produit",
    229 : "Non disponible maintenant",
    230 : "Ajouter une URL d'image",
    231 : "Description :",
    232 : "Vous pouvez utiliser des balises HTML (<p>, <br>, <h1> et autres)",
    233 : "Variantes",
    234 : "Ajouter un nouveau groupe",
    235 : "Ajouter une nouvelle variante",
    236 : "Enregistrer le produit actuel",
    237 : "Ajouter un nouveau produit",
    238 : "Unité",
    239 : "En Stock",
    240 : "pièces",
    241 : "Veuillez sélectionner une variante",
    242 : "Enregistrer groupe",
    243 : "Ajouter un groupe",
    244 : "Nom du groupe",
    245 : "Aperçu",
    246 : "URL",
    247 : "Ajouter une image",
    248 : "Nom de la variante",
    249 : "Ajouter une image de la galerie (optionnel)",
    250 : "ou",
    251 : "Ajouter l'URL de l'image (optionnel)",
    252 : "influence sur le prix +/-",
    253 : "Enregistrer la variante",
    254 : "Ajouter une variante",
    255 : "Veuillez sélectionner une action",
    256 : "l'influence doit commencer par + ou -",
    257 : "Fermer",
    258 : "Ajouter une image de la caméra",
    259 : "Ajouter une image de la caméra (facultatif)",
    260 : "Veuillez télécharger l'image",
    261 : "Annuler",
    262 : "Vous avez dépassé la limite du nombre de services. Contactez le support pour plus d'informations.",
    263 : "Arbre des catégories",
    264 : "Le prix ne peut pas être égal à 0",
    265 : "Vous avez dépassé la limite du nombre d'addons sur un service. Contactez le support pour plus d'informations.",
    266 : "Vous avez dépassé la limite du nombre de produits. Contactez le support pour plus d'informations.",
    267 : "Montant minimum de commande",
    268 : "Montant maximum de la commande",
    269 : "Paramètres",
    270 : "Définir les montants minimum et maximum de commande",
    271 : "Veuillez saisir le montant minimum de commande",
    272 : "Veuillez entrer le montant maximum de la commande",
    273 : "Autoriser la réservation uniquement si le client se trouve dans la zone de travail du fournisseur",
    274 : "@ ModjiDep Fournisseur 2022",
    275 : "Par TigerSoft",
    276 : "Chargement des messages...",
    277 : "OK",
    278 : "Vérifiez votre connexion Internet !",
    279 : "De l'utilisateur :",
    280 : "Nouvelle demande",
    281 : "Le statut de la demande a été modifié",
    282 : "État actuel: Annulée",
    283 : "État actuel: Terminée",
    284 : "Prêt",
    285:"terminé",
    286 : "En attente",
    287 : "Aucune notification",
    288 : "Image et nom de votre profil",
    289 : "Cette image et ce nom de votre profil apparaîtront sur toutes vos offres de services publiées dans les différentes catégories de votre choix. Choisissez donc une photo et un nom suffisamment décents et appropriés pour inciter les clients qui voient vos offres à vous choisir.",
    290 : "Invisible",
    291 : "Publier",
    292 : "Indisponible",
    293 : "Supprimer",
    294 : "Publier",
    295 : "Accueil",
    296 : "Disponible",
    297 : "Rendre Disponible",
    298 : "Rendre Indisponible",
    299 : "Service",
    230 : "Supprimer votre compte",
    231 : "Attention si vous confirmez, vos données seront supprimées et vous ne pouvez plus les restaurer. cette action est irréversible.",

  };









  Map<int, String> langAra = {
    0: "ModjiDep الموفر" ,
    1: "الموفر" ,
    2: "إرسال" ,
    3: "اللغة" ,
    4: "اللغة المفضلة" ,
    5: "حدد اللغة المفضلة" ,
    6: "تسجيل الدخول الآن" ,
    7: "البريد الإلكتروني" ,
    8: "أدخل بريدك الإلكتروني" ,
    9: "كلمة المرور" ,
    10: "أدخل كلمة المرور الخاصة بك" ,
    11: "متابعة" ,
    12: "تسجيل" ,
    13: "أو متابعة" ,
    14: "تسجيل" ,
    15: "في أقل من دقيقة" ,
    16: "الاسم" ,
    17: "أدخل الاسم" ,
    18: "تأكيد كلمة المرور" ,
    19: "التحقق" ,
    20: "رقم الهاتف" ,
    21: "أدخل رقم هاتفك" ,
    22: "سنرسل رمز التحقق." ,
    23: "لقد أرسلنا رمز التحقق المكون من 6 أرقام." ,
    24: "أدخل الرمز" ,
    25: "أدخل الرمز المكون من 6 أرقام" ,
    26: "دردشة" ,
    27: "التاريخ" ,
    28: "الحساب" ,
    29: "اكتب رسالتك ..." ,
    30: "في أي وقت" ,
    31: "القادمة" ,
    32: "مكتمل",
    33: "ملغاة",
    34: "جديد" ,
    35: "ملغاة",
    36: "مكتمل" ,
    37: "مقبولة" ,
    38: "اتصل الآن" ,
    39: "رسالة" ,
    40: "قبول" ,
    41: "بدء عمل" ,
    42: "اكتمل العمل" ,
    43: "انتظار التأكيد من العميل" ,
    44: "معرف الحجز" ,
    45: "تم استلام الطلب" ,
    46: "الوقت" ,
    47: "تم تأكيد الحجز" ,
    48: "تم التأكيد في",
    49: "بدء عمل" ,
    50: "مجدول في" ,
    51: "اكتملت الوظيفة" ,
    52: "سيظهر الدفع هنا" ,
    53: "التسعير" ,
    54: "الكمية" ,
    55: "مبلغ الضريبة" ,
    56: "المجموع" ,
    57: "اضغط لعرض الملف الشخصي" ,
    58: "مراجعات",
    59: "اقرأ الكل" ,
    60: "تغيير اللغة" ,
    61: "تعيين لغتك المفضلة" ,
    62: "أدخل بريدك الإلكتروني" ,
    63: "العنوان" ,
    64: "أدخل عنوان العملاء" ,
    65: "الوصف" ,
    66: "أدخل وصفًا موجزًا ​​عنك" ,
    67: "حفظ" ,
    68: "تغيير كلمة المرور" ,
    69: "كلمة المرور الجديدة" ,
    70: "أدخل كلمة المرور" ,
    71: "تأكيد كلمة المرور الجديدة" ,
    72: "تغيير كلمة المرور" ,
    73: "ملفي الشخصي" ,
    74: "كل شيء عنك" ,
    75: "متوسط ​​التقييمات" ,
    76: "تمكين الوضع الداكن" ,
    77: "تعيين الوضع المفضل لك" ,
    78: "المحفظة" ,
    79: "اعرف أرباحك" ,
    80: "محفظتي" ,
    81: "حمل أفضل أعمالك" ,
    82: "نهج الخصوصية" ,
    83: "تعرف على سياسة الخصوصية الخاصة بنا" ,
    84: "من المعرض",
    85: "من الكاميرا" ,
    86: "تحذف" ,
    87: "ضع غير مرئي" ,
    88: "الرصيد المتاح" ,
    89: "الإخطارات" ,
    90: "الكثير من المعلومات المهمة" ,
    91: "تسجيل الخروج" ,
    92: "إنهاء الجلسة" ,
    93: "الرجاء إدخال البريد الإلكتروني" ,
    94: "الرجاء إدخال كلمة المرور" ,
    95: "المستخدم غير موجود",
    96: "تم تعطيل المستخدم. اتصل بالمسؤول للحصول على مزيد من المعلومات.",
    97: "كلمات المرور غير متساوية" ,
    98: "البريد الإلكتروني خاطئ" ,
    99: "المستخدم لا ينشئ" ,
    100: "لقد تم إنشاء حسابك. بعد الإشراف سيتم تفعيل حسابك. سنبلغك بذلك.",
    101: "الدردشة عبر الإنترنت" ,
    102: "بحث" ,
    103: "رسالة دردشة" ,
    104: "الإخطارات" ,
    105: "الكثير من المعلومات المهمة" ,
    106: "اليوم" ,
    107: "غير موجود ..." ,
    108: "نبذة عنا" ,
    109: "تعرف علينا" ,
    110: "الشروط والأحكام" ,
    111: "الشروط والأحكام المعروفة" ,
    112: "أدخل اسمك" ,
    113: "أدخل تأكيد كلمة المرور" ,
    114: "تم تغيير كلمة المرور" ,
    115: "الرجاء إدخال الاسم" ,
    116: "البيانات المحفوظة" ,
    117: "تم تغيير حالة الحجز" ,
    118: "الآن الحالة:" ,
    119: "حسب الزبون" ,
    120: "حسب المزود" ,
    121: "بواسطة المسؤول",
    122: "تحويل الأموال" ,
    //123: "صفحتي" ,
    123 : "صورة واسم عروض خدمتي",
    124: "تحرير معلومات الموفر" ,
    125: "الاثنين" ,
    126: "الثلاثاء" ,
    127: "الأربعاء" ,
    128: "الخميس" ,
    129: "الجمعة" ,
    130: "السبت" ,
    131: "الأحد" ,
    132: "المعارض" ,
    133: "تحرير" ,
    134: "حفظ" ,
    135: "أدخل هاتفك" ,
    136: "أدخل عنوان صفحة الويب الخاصة بك" ,
    137: "أدخل عنوان Instagram الخاص بك" ,
    138: "أدخل عنوان Telegram الخاص بك" ,
    139: "تغيير" ,
    140: "إضافة من لوح المطبخ" ,
    141: "إضافة من الكاميرا" ,
    142: "خدماتي المنشورة" ,
    143: "تحرير معلومات الخدمة" ,
    144: "خدمة البحث" ,
    145: "هل تريد حذف هذا العنصر؟ لا يمكنك استرداد هذا العنصر." ,
    146: "لا" ,
    147: "هذا هو الوضع التجريبي. لا يمكنك تعديل هذا القسم" ,
    148: "تحرير الخدمة" ,
    149: "مرئي" ,
    150: "تحديد اللغة" ,
    151: "الضرائب" ,
    152: "عنوان الوصف" ,
    153: "السعر" ,
    154: "سعر الخصم" ,
    155: "وحدة السعر" ,
    156: "كل ساعة" ,
    157: "ثابت" ,
    158: "حدد صورة" ,
    159: "الإضافات" ,
    160: "إضافة" ,
    161: "المعرض" ,
    162: "تم حذف الصورة" ,
    163: "إضافة صورة من المعرض" ,
    164: "مدة الخدمة" ,
    165: "دقيقة",
    166: "مختارة فقط" ,
    167: "الفئات" ,
    168: "الموفرون" ,
    169: "حفظ الخدمة الحالية" ,
    170: "الرجاء إدخال السعر" ,
    171: "الرجاء تحديد المزود" ,
    172: "الرجاء إدخال الفئة" ,
    173: "حفظ الملحق",
    174: "إغلاق" ,
    175: "تحديد" ,
    176: "سيتم حذف الملحق من كافة الخدمات في الموفر الحالي. هل تريد حذف هذا العنصر؟ لن تتمكن من استرداد هذا العنصر." ,
    177: "حذف البيانات" ,
    178: "انشر خدمة جديدة" ,
    179: "منطقة عملي" ,
    180: "تحرير منطقة عملك" ,
    181: "حذف الحالي" ,
    182: "هل نسيت كلمة المرور؟" ,
    183: "إعادة تعيين كلمة المرور" ,
    184: "إرسال كلمة مرور جديدة" ,
    185: "تم إرسال البريد الإلكتروني الخاص بإعادة تعيين كلمة المرور. يرجى التحقق من بريدك.",
    186: "تاريخ" ,
    187: "الرجاء إدخال الهاتف" ,
    188: "يرجى ترك معلومات لنا لتسهيل العمل معك." ,
    189: "اسم المزود" ,
    190: "خدمة منزلية" ,
    191: "تسجيل الدخول" ,
    192: "الهاتف" ,
    193: "تعيين منطقة العمل الخاصة بي" ,
    194: "تعيين شعار الموفر" ,
    195: "الرجاء إدخال اسم المزود" ,
    196: "الرجاء إدخال الوصف" ,
    197: "الرجاء إدخال العنوان" ,
    198: "الرجاء تحميل شعار الموفر" ,
    199: "الرجاء تحديد منطقة العمل" ,
    200: "الرجاء تحديد الفئة التي ستعمل بها" ,
    201: "الرجاء إدخال تسجيل الدخول" ,
    202: "طريقة الدفع" ,
    203: "المجموع الفرعي" ,
    204: "خصم" ,
    205: "يجب أن يكون المستخدم مزودًا" ,
    206: "لم يتم العثور على معلومات الموفر" ,
    207: "هل أنت متأكد أنك تريد الخروج؟",
    208: "خروج" ,
    209: "على الخريطة" ,
    210: "موقع العميل" ,
    211: "عنوان العميل" ,
    212: "تمكين الإعلام" ,
    213: "الموفر متوفر / غير متوفر" ,
    214: "تعطيل مؤقت لحسابك" ,
    215: "ضريبة القيمة المضافة / الضرائب" ,
    216: "المبلغ الإجمالي" ,
    217: "الحجز في" ,
    218: "اسم العميل" ,
    219: "إلى المسؤول",
    220: "إلى المزود" ,
    221: "ضريبة / ضريبة القيمة المضافة" ,
    222: "العوائد" ,
    223: "التوازن" ,
    224: "أوامر" ,
    225: "منتجاتي" ,
    226: "تحرير معلومات المنتجات" ,
    227: "بحث في هذه القائمة" ,
    228: "إنشاء منتج جديد" ,
    229: "غير متوفر الآن" ,
    230: "إضافة عنوان URL للصورة" ,
    231: "الوصف:" ,
    232: "يمكنك استخدام علامات HTML (<p> , <br> , <h1> وغيرها)" ,
    233: "المتغيرات" ,
    234: "إضافة مجموعة جديدة" ,
    235: "إضافة متغير جديد" ,
    236: "حفظ المنتج الحالي" ,
    237: "إضافة منتج جديد" ,
    238: "الوحدة" ,
    239: "متوفر",
    240: "قطعة" ,
    241: "الرجاء تحديد البديل" ,
    242: "حفظ المجموعة" ,
    243: "إضافة مجموعة" ,
    244: "اسم المجموعة" ,
    245: "معاينة" ,
    246: "URL" ,
    247: "إضافة صورة" ,
    248: "الاسم المتغير" ,
    249: "إضافة صورة من المعرض (اختياري)" ,
    250: "أو" ,
    251: "إضافة عنوان URL للصورة (اختياري)" ,
    252: "التأثير على السعر +/-" ,
    253: "حفظ المتغير" ,
    254: "إضافة متغير" ,
    255: "الرجاء تحديد المخزون" ,
    256: "يجب أن يبدأ التأثير بـ + أو -" ,
    257: "إغلاق" ,
    258: "إضافة صورة من الكاميرا" ,
    259: "إضافة صورة من الكاميرا (اختياري)" ,
    260: "الرجاء تحميل الصورة" ,
    261: "إلغاء" ,
    262: "لقد تجاوزت الحد الأقصى لعدد الخدمات. لمزيد من المعلومات اتصل بالدعم." ,
    263: "شجرة الفئات" ,
    264: "لا يمكن أن يكون السعر 0" ,
    265: "لقد تجاوزت الحد الأقصى لعدد الوظائف الإضافية في خدمة واحدة. اتصل بالدعم لمزيد من المعلومات." ,
    266: "لقد تجاوزت الحد الأقصى لعدد المنتجات. اتصل بالدعم لمزيد من المعلومات." ,
    267: "الحد الأدنى لمبلغ الطلب" ,
    268: "الحد الأقصى لمبلغ الطلب" ,
    269: "إعدادات" ,
    270: "تعيين الحد الأدنى لمبالغ أوامر AMD القصوى" ,
    271: "الرجاء إدخال الحد الأدنى لمبلغ الطلب" ,
    272: "الرجاء إدخال الحد الأقصى لمبلغ الطلب" ,
    273: "السماح بالحجز فقط إذا كان العميل موجودًا في منطقة عمل المزود" ,
    274: "مورد ModjiDep",
    275: "بواسطة TigerSoft" ,
    276: "تحميل الرسائل ...",
    277: "حسنًا" ,
    278: "تحقق من اتصالك بالإنترنت!" ,
    279: "من المستخدم:",
    280 : "طلب جديد",
    281 : "تم تغيير حالة الطلب",
    282: "الحالة الحالية: ملغاة",
    283: "الوضع الحالي: مكتمل",
    284: "جاهز",
    285:"إنهاء",
    286: "الانتظار",
    287 : "لا يوجد إشعار",
    288 : "صورة ملفك الشخصي واسمك",
    289 : "ستظهر هذه الصورة واسم ملف التعريف الخاص بك على جميع عروض الخدمات الخاصة بك المنشورة في الفئات المختلفة التي تختارها. لذا اختر صورة واسمًا لائقين ومناسبين بما يكفي لإغراء العملاء الذين يرون عروضك ليختاروك.",
    290: "غير مرئي",
    291: "نشر",
    292: "غير متوفره",
    293: "حذف",
    294: "ينشر",
    295: "ترحيب",
    296: "متوفرة",
    297: "إتاحة" ,
    298: "جعله غير متاح" ,
    299 : "خدمة",
    230 : "حذف حسابك",
    231 : "كن حذرًا إذا قمت بالتأكيد ، سيتم حذف بياناتك ولن يمكنك استعادتها بعد الآن. هذا العمل لا رجوع فيه.",
  };







  Map<String, dynamic>? defaultLang;

  setLang(Map<String, dynamic> _def, String _locale, BuildContext context, TextDirection _direction){
    defaultLang = _def;
    locale = _locale;
    direction = _direction;
    Provider.of<LanguageChangeNotifierProvider>(context,listen:false).changeLocale(locale);
  }

  String get(int id){
    if (defaultLang == null) {
      return langEng[id] == null ? "" : langEng[id]!;
    }else{
      /*
      if (defaultLang![id.toString()] != null) {
        return defaultLang![id.toString()];
      }
      */
      if(locale == "en") {
        return langEng[id] == null ? "" : langEng[id]!;
      }else if(locale == "fr"){
        return langFra[id] == null ? "" : langFra[id]!;
      }else if (locale == "ar"){
        return langAra[id] == null ? "" : langAra[id]!;
      }else{
        return langFra[id] == null ? "" : langEng[id]!;
      }

    }
  }

}

